version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./django/app:/app
      - ./config/nginx:/etc/nginx.conf.d
    depends_on:
      - django_app

  mysql_db:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    networks: 
       - app-tier
    volumes:
       - ./mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234

  django_app:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
      # settings.py 환경분리 되어있어 settings를 지정해야하는 경우 다음과 같이 추가 입력
      # [--env DJANGO_SETTINGS_MODULE='<django_project>.settings.production']
    expose:
      - "8000"
    depends_on:
      - mysql_db
    links:
      - mysql_db:mysql_db
#    networks:
#      - app-tier
    restart: always
    volumes:
      - ./django/app:/app
    env_file:
      - ./django/env.dev

networks:
  app-tier:
    driver: bridge
